# Generated by Django 5.1.6 on 2025-03-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='musicpicgallery_img/')),
                ('pic2', models.ImageField(upload_to='musicpicgallery_img/')),
                ('pic3', models.ImageField(upload_to='musicpicgallery_img/')),
            ],
        ),
    ]
