# Generated by Django 5.1.6 on 2025-03-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='pic1',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='pic3',
        ),
    ]
