# Generated by Django 5.1.6 on 2025-03-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_pic1_gallery_pic_remove_gallery_pic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
