# Generated by Django 5.1.6 on 2025-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='pic', max_length=50),
        ),
    ]
