# Generated by Django 5.1.6 on 2025-03-25 08:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='Trackmusics/')),
                ('file', models.FileField(upload_to='tracks/')),
                ('status', models.BooleanField(choices=[(True, 'Publish'), (False, 'Draft')], default=False)),
            ],
        ),
    ]
