# Generated by Django 5.1.6 on 2025-04-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Azmoon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='start_time',
        ),
    ]
