# Generated by Django 5.1.4 on 2025-03-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
