# Generated by Django 5.1.6 on 2025-03-27 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmoshavere',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
        migrations.AddField(
            model_name='personalmoshavere',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
