# Generated by Django 5.1.6 on 2025-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moshavere', '0002_businessmoshavere_content_personalmoshavere_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardMoshavere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='moshavere_img/')),
            ],
        ),
    ]
