# Generated by Django 5.1.6 on 2025-03-30 08:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('بیوگرافی', ckeditor.fields.RichTextField()),
                ('تحصیلات_دانش', ckeditor.fields.RichTextField()),
                ('فعالیت', ckeditor.fields.RichTextField()),
                ('علاقمندی', ckeditor.fields.RichTextField()),
                ('هنر', ckeditor.fields.RichTextField()),
                ('مهارت', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
